chessMenImg["BB"] = "bishop_black.png"
chessMenImg["WB"] = "bishop_white.png"
chessMenImg["BK"] = "king_black.png"
chessMenImg["WK"] = "king_white.png"
chessMenImg["WKn"] = "kinght_white.png"
chessMenImg["BKn"] = "knight_black.png"
chessMenImg["BP"] = "pawn_black.png"
chessMenImg["WP"] = "pawn_white.png"
chessMenImg["BQ"] = "queen_black.png"
chessMenImg["WQ"] = "queen_white.png"
chessMenImg["BR"] = "rook_black.png"
chessMenImg["WR"] = "rook_white.png"

